import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import "./globals.css";
import { AuthProvider } from "./contexts/AuthContext";

const geist = localFont({
	src: "./fonts/Geist-Regular.woff2",
	variable: "--font-geist",
	weight: "100 900",
});

const geistMono = localFont({
	src: "./fonts/GeistMono-Regular.woff2",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geist.variable} ${geistMono.variable} antialiased`}
			>
				<AuthProvider>
					<Toaster position="top-right" richColors closeButton />
					{children}
				</AuthProvider>
			</body>
		</html>
	);
}
