namespace: watchtower

global:
    imagePullPolicy: Always
    AUTH_URL: http://auth-service
    INCIDENT_URL: http://incident-service
    FRONTEND_URL: http://frontend
    NODE_ENV: production

postgres:
    enabled: true
    image: postgres:18-alpine
    user: postgres
    storage: 5Gi

redis:
    enabled: true
    image: redis:8.2-alpine
    config:
        host: redis
        port: 6379
    resources:
        requests:
            cpu: 250m
            memory: 128Mi
        limits:
            cpu: 500m
            memory: 512Mi

auth:
    replicas: 2
    image:
        repository: ghcr.io/rohan1337/watchtower-auth-service
        tag: latest
    port: 3001
    config: {}
    resources:
        requests:
            cpu: 250m
            memory: 128Mi
        limits:
            cpu: 500m
            memory: 512Mi
    autoscaling:
        minReplicas: 2
        maxReplicas: 10
        targetCPUUtilization: 70

incident:
    replicas: 2
    image:
        repository: ghcr.io/rohan1337/watchtower-incident-service
        tag: latest
    port: 3003
    resources:
        requests:
            cpu: 250m
            memory: 128Mi
        limits:
            cpu: 500m
            memory: 512Mi
    autoscaling:
        minReplicas: 2
        maxReplicas: 10
        targetCPUUtilization: 70

notification:
    replicas: 2
    image:
        repository: ghcr.io/rohan1337/watchtower-notification-service
        tag: latest
    config:
        smtpHost: smtp.gmail.com
    resources:
        requests:
            cpu: 250m
            memory: 128Mi
        limits:
            cpu: 500m
            memory: 512Mi
    autoscaling:
        minReplicas: 2
        maxReplicas: 10
        targetCPUUtilization: 70

frontend:
    replicas: 2
    image:
        repository: ghcr.io/rohan1337/watchtower-frontend
        tag: latest
    port: 3000
    configs:
        authBaseUrl: "/api"
        incidentBaseUrl: "/api"
    resources:
        requests:
            cpu: 250m
            memory: 128Mi
        limits:
            cpu: 500m
            memory: 512Mi
    autoscaling:
        minReplicas: 2
        maxReplicas: 10
        targetCPUUtilization: 70

ingress:
    enabled: true
    host: watchtower.local
    tlsSecretName: watchtower-tls
