apiVersion: v1
kind: Secret
metadata:
    name: auth-secret
    # prettier-ignore
    namespace: {{ .Values.namespace }}
type: Opaque
stringData:
    DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/auth_service_db"
    JWT_ACCESS_SECRET: "{{ .Values.auth.config.jwtAccessSecret }}"
    JWT_REFRESH_SECRET: "{{ .Values.auth.config.jwtRefreshSecret }}"
