apiVersion: v1
kind: ConfigMap
metadata:
    name: auth-config
    # prettier-ignore
    namespace: {{ .Values.namespace }}
data:
    PORT: "{{ .Values.auth.port }}"
    REDIS_HOST: "{{ .Values.redis.config.host }}"
    REDIS_PORT: "{{ .Values.redis.config.port }}"
    FRONTEND_URL: "{{ .Values.global.FRONTEND_URL }}"
    NODE_ENV: "{{ .Values.global.NODE_ENV }}"
