apiVersion: v1
kind: Service
metadata:
    name: incident-service
    # prettier-ignore
    namespace: {{ .Values.namespace }}
spec:
    type: ClusterIP
    selector:
        app: incident-service
    ports:
        # prettier-ignore
        - port: {{ .Values.incident.port }}
          targetPort: {{ .Values.incident.port }}
