apiVersion: v1
kind: Secret
metadata:
    name: notification-secret
    # prettier-ignore
    namespace: {{ .Values.namespace }}
type: Opaque
stringData:
    SMTP_USER: "{{ .Values.notification.config.smtpUser }}"
    SMTP_PASS: "{{ .Values.notification.config.smtpPass }}"
