apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-init-sql
    # prettier-ignore
    namespace: {{ .Values.namespace }}
data:
    init.sql: |
        CREATE DATABASE auth_service_db;
        CREATE DATABASE incident_service_db;
