apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    # prettier-ignore
    namespace: {{ .Values.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  # prettier-ignore
                  image: {{ .Values.postgres.image }}
                  ports:
                      - containerPort: 5432
                  livenessProbe:
                      exec:
                          command:
                              - pg_isready
                              - -U
                              - postgres
                      initialDelaySeconds: 20
                      periodSeconds: 10
                  startupProbe:
                      exec:
                          command:
                              - pg_isready
                              - -U
                              - postgres
                      failureThreshold: 30
                      periodSeconds: 10
                  readinessProbe:
                      exec:
                          command:
                              - pg_isready
                              - -U
                              - postgres
                      initialDelaySeconds: 10
                      periodSeconds: 5
                  envFrom:
                      - secretRef:
                            name: postgres-secret
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
                      - name: init-sql
                        mountPath: /docker-entrypoint-initdb.d
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                      claimName: postgres-pvc
                - name: init-sql
                  configMap:
                      name: postgres-init-sql
